# Generated by Django 3.0.7 on 2020-11-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201122_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='quiz_taken',
            new_name='quiz_taker',
        ),
    ]
